version: 2
jobs:
  install:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: yarn
      - save_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
  pkg-ok:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run:
          name: Install dependencies
          command: yarn
      - run: yarn pkg-ok
  lint:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run: yarn lint
  test:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run: yarn test
  test6:
    docker:
      - image: circleci/node:6
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run: yarn test
  testNext:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run: yarn test

  release:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run: |
          git config --global user.name "rucasbot"
          git config --global user.email "rucasbot@gmail.com"
          yarn release

  publish:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run: |
          printf "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
          SEMVER=$(echo "$CIRCLE_TAG" | cut -c2-)
          yarn np $SEMVER

workflows:
  version: 2
  build_lint_test:
    jobs:
      - install
      - pkg-ok: 
          requires:
            - install
      - lint:
          requires:
            - install
      - test:
          requires:
            - install
      - test6:
          requires:
            - install
      - testNext:
          requires:
            - install
      - release:
          requires:
            - pkg-ok 
            - lint
            - test
            - test6
            - testNext
          filters:
            branches:
              ignore: /.*/
            # only act on version tags
            tags:
              only: /^v.*/
      - publish:
          requires:
            - pkg-ok 
            - lint
            - test
            - test6
            - testNext
          filters:
            branches:
              ignore: /.*/
            # only act on version tags
            tags:
              only: /^v.*/
